### ISSUE TITLE
Possible Name mismatch for the S-300PMU1 40B6MD sr

### ISSUE THREAD

**Issue by walder** [Auranis/HighDigitSAMs#12]
This radar is identified as a SAM SA-20 S-300PMU1 SR **5N66E** in game. The unit name in LUA however is S-300PMU1 **40B6MD** sr.

```
GT.Name = "S-300PMU1 40B6MD sr";
GT.DisplayName = _("SAM SA-20 S-300PMU1 SR 5N66E");
GT.Rate = 20;

local ws = 0;
for i = 1,24 do -- 24 target trackers
    ws = GT_t.inc_ws();
	GT.WS[ws] = {}
    GT.WS[ws].pos = {0,42.158,0}
	GT.WS[ws].angles = {
					{math.rad(180), math.rad(-180), math.rad(-10), math.rad(10)},
					};
    GT.WS[ws].omegaY = 3
    GT.WS[ws].omegaZ = 3
    GT.WS[ws].LN = 
    {
        {
        type = 101,
		reflection_limit = 0.049,
        distanceMax = GT.sensor.max_range_finding_target,
		ECM_K = 0.65,
        min_trg_alt = 5,
        max_trg_alt = 3000,
        reactionTime = 3;
        },
    }
end --for
```

**Comment by LetMePickThat** [comment]
By default, Eagle Dynamics used the name of the mast to describe various radars of the S-300PS. The 30N6 FCR is called 40B6M, while the 5N66 is called the 40B6MD. We kept that naming convention for the 300PMU1 and the revamped 300PS, as it allows us to add the truck-based versions of the same radars.

**Comment by LetMePickThat** [comment]
@walder is that still an issue or can I close it?

**Comment by walder** [comment]
you can close it 👍
