### ISSUE TITLE
Question:  Any plans for bluefor SAM systems?

### ISSUE THREAD

**Issue by MobiSev** [Auranis/HighDigitSAMs#13]

**Comment by LetMePickThat** [comment]
Upgraded Patriot has always been on the roadmap. It will be added when and if Auranis get the free time to do it, or somebody else decides to step up and contribute it themselves. Right now I am working on implementing a SAMP/T system which should at the very least provide an interesting western option. For now our next plans are advanced flight models for the current missiles in the pack.
