### ISSUE TITLE
[v1.4.0] IC check fails

### ISSUE THREAD

**Issue by hawaiianryan808** [Auranis/HighDigitSAMs#14]
IC error with HighDigitSAMs `v1.4.0`:

`models/48h6e2.edm @ c:/users/XXXX/saved games/dcs.openbeta/mods/tech/highdigitsams/shapes`

Just like the error with HighDigitSAMs `v1.3.0` that required the `v1.3.1` hotfix.

Downloaded from: https://github.com/Auranis/HighDigitSAMs/releases/download/v1.4.0/HighDigitSAMs_v1_4_0.zip

**Comment by LetMePickThat** [comment]
That's interesting, V1.4.0 doesn't fail the IC check on my side:

![image](https://user-images.githubusercontent.com/72825026/106322522-3b91b580-6276-11eb-8922-df91e62017da.png)
![image](https://user-images.githubusercontent.com/72825026/106322602-5bc17480-6276-11eb-93fc-af90dfcde8a2.png)

I'll take a look.

**Comment by LetMePickThat** [comment]
From what I see, the 48h6e2.edm file stuck after an internal update, as it coexists with the new, IC-compliant 48h6e2_hds.edm. A simple solution is to just delete the 48h6e2.edm file, as it is not used anymore. I will make these changes on the Main and Dev branches.

**Comment by Auranis** [comment]
Fixed locally, will put out another hotfix tomorrow. Sorry this one crept back in, guys.
