### ISSUE TITLE
Question: how did you make the multi-stage booster for the 9M82M?

### ISSUE THREAD

**Issue by jhgunter** [Auranis/HighDigitSAMs#18]
Hi! First of all, thanks for putting this mod together — it's really cool to have no only newer variants of the SAMs, but also nice/updated 3D models.

I'm helping out with another DCS mod (the [HMS Duncan](https://en.wikipedia.org/wiki/HMS_Duncan_(D37))) and its main SAM armament is the [Aster](https://en.wikipedia.org/wiki/Aster_(missile_family)), which has a two-stage design with a detachable booster. I've been trying to figure out how to set up the code so that the booster properly detaches after it runs out of fuel, but I haven't figured it out yet. I know the 9M82M from this mod's S-300VM has a working detachable booster, so I was wondering if you could share some info about how you did that (what Lua code was required, if there was any special configuration on the model side, etc.).

Thanks in advance! Let me know if I can clarify anything about my question.

**Comment by LetMePickThat** [comment]
As a matter of fact, I've already made an Aster 30 for the SAMP/T system, with the help of ERO. Send me a message on Discord - Fox (HDSM)#1022 -, and I'll share that with you.

**Comment by LetMePickThat** [comment]
![Digital Combat Simulator  Black Shark Screenshot 2020 10 29 - 23 34 47 99](https://user-images.githubusercontent.com/72825026/108621394-acba2800-7432-11eb-9f11-43d40a480714.jpg)
![Digital Combat Simulator  Black Shark Screenshot 2020 10 29 - 23 31 20 28](https://user-images.githubusercontent.com/72825026/108621395-ad52be80-7432-11eb-92d1-6e308e51f58f.jpg)
