### ISSUE TITLE
S300 VM Missile 82 

### ISSUE THREAD

**Issue by StrikerOneOne** [Auranis/HighDigitSAMs#21]
S-300 vm always explode a few moments later when launched for no reason

**Comment by StrikerOneOne** [comment]
Le missile 9M82 du S300VM explose tout seul au bout de quelques secondes (Sans raisons apparente)

**Comment by LetMePickThat** [comment]
Pourrais-je avoir une vidéo? C'est la première fois qu'on mentionne ce problème, et je ne l'ai pas chez moi.

**Comment by StrikerOneOne** [comment]
Je vais retester ça dans la nuit c'était sur Syrie, peut être que les scuds
était repérer de trop prêt et que le missile partait trop tard donc il
s'autodetruisait mais en laissant les batterie au même endroit les missile
pétait avant d'atteindre tout ce que je lui envoyait dessus, chasseur,
tupolev, b52, j'ai tester sur caucase aujourd'hui et R.a.s le 82
fonctionnais à la perfection d'ailleurs le mod est génial je me régal et
j'espère qu'il sera partout à la longue
