### ISSUE TITLE
IC problem

### ISSUE THREAD

**Issue by Biggus22** [Auranis/HighDigitSAMs#24]
Hi
I'm getting the following message with an integrity check failure.

models/9m82.edm @ c:/users/j7517/saved games/dcs.openbeta/mods/tech/highdigitsams/shapes

It's a bit odd because I played for hours yesterday with no problems and today I'm getting kicked off my dedi server.

Love the mod btw.

**Comment by LetMePickThat** [comment]
Download and install the lastest Dev branch version of the mod, this will fix the issue.
Thank you for your nice comment. :)
