### ISSUE TITLE
SA-23 is dumb on 2.7

### ISSUE THREAD

**Issue by CarlAAJ** [Auranis/HighDigitSAMs#25]
SA-23 with and without IADS appears to be dumb, doesn't fire 90% of the time, and when it does it can't keep the lock for long, trashing the missile a few seconds later.

**Comment by LetMePickThat** [comment]
Please send the associated .miz file, the system works well on my end.

![Digital Combat Simulator  Black Shark Screenshot 2021 04 15 - 17 56 33 19](https://user-images.githubusercontent.com/72825026/115148579-82669e80-a060-11eb-9fe9-45f2a650de1a.png)
![Digital Combat Simulator  Black Shark Screenshot 2021 04 15 - 17 57 00 41](https://user-images.githubusercontent.com/72825026/115148581-8692bc00-a060-11eb-83c7-f7e4b7224026.png)

**Comment by CarlAAJ** [comment]
![Screen_210419_131018](https://user-images.githubusercontent.com/23036392/115268439-a5508b80-a110-11eb-8e8e-0eb1790f9b25.png)


[Operation Iron Curtain.zip](https://github.com/Auranis/HighDigitSAMs/files/6337493/Operation.Iron.Curtain.zip)

**Comment by LetMePickThat** [comment]
The problem should be fixed in the upcoming days, when my PR gets merged. Thanks for thje bug report.
