### ISSUE TITLE
High Digit Sam - Authorization valid, expires in two days.

### ISSUE THREAD

**Issue by synackack** [Auranis/HighDigitSAMs#27]
Hello there!

Any idea why this would be popping up?

![authvalid_highdidig](https://user-images.githubusercontent.com/437656/115601563-f779e400-a2ab-11eb-8981-f96492438975.PNG)

**Comment by Auranis** [comment]
Hi Synackack,

That would most likely be a result of trying to install the mod in your main DCS directory.

The mod should be installed in either Saved Games/DCS or Saved Games/DCS.openbeta, depending on your specific configuration.

Make sure to delete the HighDigitSams folder from your DCS install directory.
