### ISSUE TITLE
ALIC Table with DED codes for HARM AGM-88C

### ISSUE THREAD

**Issue by dasrehzockt** [Auranis/HighDigitSAMs#32]
i wanted to use HARM missiles in prebriefed (PB) mode against high digit sams. but i was not able to find the corresponding "DED Codes" for the added radars.

are these implemented at all? or would those simply require the same codes as for example the S-300PS?

would be nice if you could add some info about those, thx

**Comment by LetMePickThat** [comment]
Hi @dasrehzockt !

We are looking for a way to implement custom codes for our SAMs, but in the meatime you can use the following ones: 
- SA-10/20 use 103/104/110, and SA-12/23 use 105/106

**Comment by dasrehzockt** [comment]
awesome, thanks for the info. i hope this finds it's way into the documentation/description/pdf and gets updated once you got custom ones implemented, since most people right now assume, that PB would not work for those at all.
