### ISSUE TITLE
SA-23 missiles repeatedly self-destruct with no clear reason

### ISSUE THREAD

**Issue by meltingSnowdrift** [Auranis/HighDigitSAMs#34]
When engaging aircraft, SA-23 missiles self-destruct after launch for no reason that I can understand. This occurs even with aircraft flying in a straight line set to not react to threats.

The attached zip file contains a track demonstrating this issue. Although a MiG-25 was used as the target here, I have also observed this happen for slower aircraft. It does not appear to occur when engaging Scud missiles, though i am not entirely sure of this.

[SA-23 problem.zip](https://github.com/Auranis/HighDigitSAMs/files/6473994/SA-23.problem.zip)

**Comment by LetMePickThat** [comment]
I'll take a look, thanks.

**Comment by dorianr666** [comment]
still present.

**Comment by LetMePickThat** [comment]
> still present.

Can you send me the scenario you're using?
If the missiles self-destroy because the radar looses the LOS to the target, that's an intended behavior. This can happen for long range shots, so having the scenario would help diagnose the problem (I can't reproduce the bug on my end).
