### ISSUE TITLE
Minor visual issue with SA-20B

### ISSUE THREAD

**Issue by meltingSnowdrift** [Auranis/HighDigitSAMs#35]
While testing the SA-20B system, I noticed that the missiles continue accelerating for some time after they stop emitting smoke. Is this intentional? If not, can it be fixed?

Reproducing this issue should be trivial, so no steps are needed. It happens every time an SA-20B missile is fired.

**Comment by LetMePickThat** [comment]
This is a limitation of the current flight model. I could fix it, but since it will be changed when the new advanced flight model will be released, I'd rather leave it as it is for now.
