### ISSUE TITLE
ERROR   APP: Can't find score constants for (insert Missile name here)

### ISSUE THREAD

**Issue by Bones1775** [Auranis/HighDigitSAMs#39]
[dcs.log](https://github.com/Auranis/HighDigitSAMs/files/8858247/dcs.log)

seams to only occur when i'm flying a client aircraft. spectating with AI only does not throw the errors.

**Comment by YoloWingPixie** [comment]
I could not replicate this in the current version of HDS and DCS. please reopen if you are still experiencing this or have additional details
