### ISSUE TITLE
S-400 Development?

### ISSUE THREAD

**Issue by StealthySpace7** [Auranis/HighDigitSAMs#40]
Hey, I would love to see the S-400 SA-21 Triumph brought into the mod, I would also like to help out with it, I have extensive knowledge on the SAM, I also have a document outlining the entire battery, the support vehicles, Radars, missiles, ranges, quite literally everything. 

I can be reached by discord at StealthySpace7#4715 with any questions. 

Thanks all, love the mod!

**Comment by YoloWingPixie** [comment]
@StealthySpace7 Hello, I realize this is quite old at this point but the documentation is really not the limiting factor. We would need 3D models for the 5P85TE2, 96L6, 55K6E, 92N2E , 91N6E, and potentially even the 48N6E3. These models would need to be compatible with the MIT license for inclusion in this mod. Without unique models there is very little traction to get this system added to HDS.

Auranis and I have also been looking at the new missile guidance API and realistically the SA-20's missile capabilities are pushing the limits of DCS's current modeling of missile guidance.
