### ISSUE TITLE
SA-23 and SA-20A/B fire at half or less than half range

### ISSUE THREAD

**Issue by RussianSAMsite** [Auranis/HighDigitSAMs#41]
I have ran many situations trying to get them to work properly but the sa-23 and the sa-20 series fire missiles at half the possible distance so it makes using a long range sam useless if it fires at a closer range range than its intended

**Comment by Auranis** [comment]
Generally speaking, long range SAMs like the S-300 can only achieve their maximum range against very high-altitude targets. See the below example performance graph for the S-300PS, plotting target altitude vs. distance across the DLZ.
Right now we have no plans to adjust the DLZs for units in the pack.
![image](https://github.com/Auranis/HighDigitSAMs/assets/14898778/fd68fbd7-b590-4a28-9615-cca3f8e79a26)
