### ISSUE TITLE
Add a Prefix to the HighDigitSAMs in the mission editor

### ISSUE THREAD

**Issue by walder** [Auranis/HighDigitSAMs#5]
For example [HD] or something similar. This would allow mission designers to see quickly if they selected a base game unit or one from the mod.
![Screenshot 2020-12-11 173422](https://user-images.githubusercontent.com/339957/101929595-5aa98a80-3bd7-11eb-8271-3bfa014c4106.png)

**Comment by LetMePickThat** [comment]
Hi Walder !
I've tried to use that kind of method when making the SA-23, only not to do it in the end because it breaks the way SAMs are organized in the list and makes the whole thing more confusing. Maybe a suffix would do, what do you think?

**Comment by walder** [comment]
suffix would work to I guess

**Comment by Pricesswg** [comment]
Hi, a -mod suffix will help a lot to distinguish the new unit whit the old ones and will be really useful during mission editing to quick setup the air defence network

**Comment by LetMePickThat** [comment]
I'll suggest an "(mod.) suffix to @Auranis and ERO.

**Comment by MaHuJa** [comment]
The "vanilla" mod behavior is that the mod required for a unit is listed in the unit list screen.
That allows quickly finding what units cause a mission to depend on a mod.
Among vanilla units, TF-51D is a "mod" that causes the mission to require a "mod". 

Personally I'd rather the unit selection menu, F10 map, tacview, and all other places the name is likely to appear, stay clean.

**Comment by Auranis** [comment]
I'm inclined to agree with the above viewpoint. The dropdown selectors in the Mission Editor don't scale all that well, so I am concerned about the UX implications if we were to implement a suffix.

**Comment by walder** [comment]
I believe there are multiple Fields for a Unit name. One for the UI of the Mission editor and another one for type display in game.

`GT.DisplayName = _("SAM SA-20 S-300PMU1 LN 5P85DE");`
This value for example is only used in the mission Editor as far as I know.

So renaming them to
`GT.DisplayName = _("SAM SA-20 S-300PMU1 LN 5P85DE [HD]");`
would work. It should only be displayed in the drop down and its a short suffix.

**Comment by LetMePickThat** [comment]
To be fair, I'd rather keep the mod as transparent for the end user as possible. That is, stick to ED's naming conventions and not mess too much with how units are displayed in the ME. I don't know if Ero and Auranis are with me on that, but to me the best mods are the ones that do not appear to be mods to the player.
