### ISSUE TITLE
HDSM will not run

### ISSUE THREAD

**Issue by LawnDartLeo** [Auranis/HighDigitSAMs#50]
Greetings,

When properly installed (its not that hard) HDSM will not allow DCS to start.  Remove folder and DCS will start.  Is there a particular mod that HDSM conflicts with?

476 Range Targets
AM2Mat (not even sure what this is)
LLH_Counter_Insurgency
Massun92-Asset Pack
SAMPack_S-300_Series << possible culprit
SAMSitesAssetPack << possible culprit
Tacview

I thought I read that this package is compatible with the two that are indicated.

Thanks in advance!

**Comment by YoloWingPixie** [comment]
@LawnDartLeo Have you tried without SAMPack_S-300_Series? I believe that mod does cause a conflict with HDS
