### ISSUE TITLE
Partial availability in factions

### ISSUE THREAD

**Issue by MaHuJa** [Auranis/HighDigitSAMs#8]
I found all of SA-20 except launchers in the menu.
I then found the cause of this was the insurgent faction (being default selected).

It should be an all or nothing. Either a faction has all the vehicles of a particular SAM type, or it has none. 

Insurgents in particular probably shouldn't have any SA-20 units at their disposal in the first place.

**Comment by LetMePickThat** [comment]
That's a very common and easily solved issue. Of course, SA-20 units should not be available to the Insurgent faction.
I'll check every unit and make sure that they are available only to the countries that really use the system. Thank you for letting us know.

**Comment by LetMePickThat** [comment]
Fixed in my latest pull request. Should be rolled out to the public version after checking by Auranis.
